apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-tomcat
  name: eks-tomcat
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eks-tomcat
  template:
    metadata:
      labels:
        app: eks-tomcat
    spec:
      containers:
      - image: 843285683127.dkr.ecr.us-east-2.amazonaws.com/tomcat-ecr
        name: eks-tomcat
---
apiVersion: v1
kind: Service
metadata:
  name: svc-tomcat
spec:
  selector:
    app: eks-tomcat
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  clusterIP: 172.20.0.3
<<<<<<< HEAD
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-tomcat
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eks-tomcat
  targetCPUUtilizationPercentage: 50
=======

>>>>>>> 50553f580fdd87eedc216638dd52f11d0a609bdc
