apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-nginx
  name: eks-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eks-nginx
  template:
    metadata:
      labels:
        app: eks-nginx
    spec:
      containers:
      - image: 843285683127.dkr.ecr.us-east-2.amazonaws.com/nginx-ecr
        name: eks-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:843285683127:certificate/753ebc6c-3b7a-4d26-a4bc-1b5e64c0b49d
spec:
  selector:
    app: eks-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eks-nginx
  targetCPUUtilizationPercentage: 20
